name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Install project dependencies using pnpm

      - name: Build project
        run: pnpm run build # Run the build command defined in your package.json using pnpm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Third-party action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          publish_dir: ./dist # The directory containing your built website files (Vite's default)
          publish_branch: gh-pages # The branch to which the built files will be pushed
          force_orphan: true # Delete the branch if it already exists
          # cname: your-custom-domain.com # Uncomment and replace with your custom domain if you have one